### ISSUE TITLE
Error activating Windows Server 2019 in the latest version

### ISSUE THREAD

**Issue by xf22cn** [Py-KMS-Organization/py-kms#138]
After updating py kms: minimal to the latest version, use the following command to test on Win10:
.\vlmcs.exe -v -l 3 kms-server-ip
Return error message:

Request Parameters
==================

Protocol version                : 6.0
Client is a virtual machine     : No
Licensing status                : 2 (OOB grace)
Remaining time (0 = forever)    : 43200 minutes
Application ID                  : 55c92734-d682-4d71-983e-d6ec3f16059f (Windows)
SKU ID (aka Activation ID)      : 34e1ae55-27f8-4950-8877-7a03be5fb181 (Windows Server 2019 Datacenter)
KMS ID (aka KMS counted ID)     : 8449b1fb-f0ea-497a-99ab-66ca96e9a0f5 (Windows Server 2019)
Client machine ID               : 38d7cc4c-c604-4c9c-8c90-2245be50287a
Previous client machine ID      : 00000000-0000-0000-0000-000000000000
Client request timestamp (UTC)  : 2025-11-17 01:14:38
Workstation name                : we-love.ubuntu.pro
N count policy (minimum clients): 5

Connecting to 172.16.18.68:1688 ... successful

Performing RPC bind ...
... NDR32 ... BTFN ... successful
Sending activation request (KMS V6)
Fatal: No RPC response received from server

Error 0x0000071C while sending request 1 of 9
Communication failed during remote procedure call.

The above is the error output information.
I checked the output log of the server and found no information about successful activation.

The version released a few days ago also had the same issue.
Earlier versions do not have this issue and can pass testing normally.

**Comment by xf22cn** [comment]
Supplement the output logs of the server:

Mon, 17 Nov 2025 12:36:47 INFO     Connection accepted: ::ffff:172.16.18.114:59546
Mon, 17 Nov 2025 12:36:47 INFO     RPC bind request received.
Mon, 17 Nov 2025 12:36:47 INFO     RPC bind acknowledged.
Mon, 17 Nov 2025 12:36:47 INFO     Received activation request.
Mon, 17 Nov 2025 12:36:47 INFO     Received V6 request on Mon Nov 17 12:36:47 2025.
Mon, 17 Nov 2025 12:36:47 WARNING  Module 'tzlocal' or 'pytz' not available ! Request time not localized.
Mon, 17 Nov 2025 12:36:47 WARNING  Too many clients ! Fixed with 10
Mon, 17 Nov 2025 12:36:47 INFO     Machine Name: ns1.google.at
Mon, 17 Nov 2025 12:36:47 INFO     Client Machine ID: d94a8218-858a-4a31-a756-9d99f4e9d606
Mon, 17 Nov 2025 12:36:47 INFO     Application ID: Windows
Mon, 17 Nov 2025 12:36:47 INFO     SKU ID: Windows Server 2019 Datacenter
Mon, 17 Nov 2025 12:36:47 INFO     License Status: Grace Period
Mon, 17 Nov 2025 12:36:47 INFO     Request Time: 2025-11-17 04:36:47  (UTC)
Mon, 17 Nov 2025 12:36:47 INFO     Connection closed: ::ffff:172.16.18.114:59546

**Comment by xf22cn** [comment]
I checked the information and found that the activation requirement for the server is that the number of client activations must be at least 25. May I ask if this issue is caused by insufficient activation settings on the client side? I saw one sentence in the log:

Mon, 17 Nov 2025 12:36:47 WARNING Too many clients ! Fixed with 10

In previous versions, this value was set to 25
If that's the reason, I hope it can be corrected as soon as possible.
I can't thank you enough.

**Comment by didotb** [comment]
is the error really starting with `0x0`? All activation error codes start with `0xC` and `0x8`, your error code indicates a driver problem somehow.

**Comment by didotb** [comment]
I'm able to activate my newly installed Server 2019 Datacenter Core, sometimes you might need to retry multiple times if you see a `0xC` in the error code.
But as I mentioned previously, the error code given to you suggests a driver error on your Windows Server 2019.

<img width="608" height="862" alt="Image" src="https://github.com/user-attachments/assets/db7dcc66-c9a5-4638-903f-9e8e214e0ed9" />

<img width="971" height="161" alt="Image" src="https://github.com/user-attachments/assets/4f192b03-e969-4093-87d9-08095e443869" />

**Comment by xf22cn** [comment]
I used the program "vlmcs-Windows-x64.exe" on a Windows 10 system for testing.

The test was performed in the command prompt (cmd).

The command used was:

.\vlmcs.exe -v -l 3  kms-server-ip

This test passed easily in earlier versions without errors.

However, it failed in the newer version. I tested it more than 10 times, and it never returned a successful activation message.

Please refer to my previous information for error messages and server log output.

**Comment by xf22cn** [comment]
I might need to install a Windows Server 2019 virtual machine for testing?

I'll start this test later, but I'm not sure I can report the results quickly.

I've been a bit busy these past few days…

**Comment by xf22cn** [comment]
I used a different testing method.

I installed another docker-kms service program on the same Debian host. The link is as follows:

https://github.com/11notes/docker-kms

The test passed.

I think this is indeed an issue that might need to be fixed.

**Comment by xf22cn** [comment]
Today I installed Windows Server 2019 Standard Edition in a virtual machine for testing, but unfortunately, activation failed.

A screenshot of the error message is as follows:

<img width="478" height="351" alt="Image" src="https://github.com/user-attachments/assets/2f19e3df-bb9e-4ac5-8ca7-149798326547" />

<img width="1096" height="533" alt="Image" src="https://github.com/user-attachments/assets/7a2142ac-e059-40c0-9a9c-2d92a41202a1" />

The server logs are as follows:

Mon, 17 Nov 2025 22:14:09 INFO     Connection accepted: ::ffff:172.16.18.107:49698
Mon, 17 Nov 2025 22:14:09 INFO     RPC bind request received.
Mon, 17 Nov 2025 22:14:09 INFO     RPC bind acknowledged.
Mon, 17 Nov 2025 22:14:09 INFO     Received activation request.
Mon, 17 Nov 2025 22:14:09 INFO     Received V6 request on Mon Nov 17 22:14:09 2025.
Mon, 17 Nov 2025 22:14:09 WARNING  Module 'tzlocal' or 'pytz' not available ! Request time not localized.
Mon, 17 Nov 2025 22:14:09 WARNING  Too many clients ! Fixed with 10
Mon, 17 Nov 2025 22:14:09 INFO     Machine Name: WIN-7KCV3TA5B39
Mon, 17 Nov 2025 22:14:09 INFO     Client Machine ID: 4098274c-1047-4548-bfa1-c73d9855ba2c
Mon, 17 Nov 2025 22:14:09 INFO     Application ID: Windows
Mon, 17 Nov 2025 22:14:09 INFO     SKU ID: Windows Server 2019 Standard
Mon, 17 Nov 2025 22:14:09 INFO     License Status: Notifications Mode
Mon, 17 Nov 2025 22:14:09 INFO     Request Time: 2025-11-18 03:14:07  (UTC)
Mon, 17 Nov 2025 22:14:09 INFO     Connection closed: ::ffff:172.16.18.107:49698

**Comment by xf22cn** [comment]
To add, I tried to activate it multiple times afterward by running the activation command, but it still failed.

**Comment by xf22cn** [comment]
The error message in the screenshot is:

Error: 0xC004F074 The software license server reports that it cannot activate the computer and cannot contact any key management service (KMS).For further information, please refer to the application event log.

**Comment by didotb** [comment]
that's odd, I retested mine as well using `minimal`, I still was able to activate the same server 2019 datacenter.
What's your environment variables on the py-kms?

> WARNING Too many clients ! Fixed with 10

I also see the same thing on my logs, but activation still isn't a problem.

**Comment by didotb** [comment]
I just checked with an older image, and the warning message `WARNING Too many clients ! Fixed with 10` exists only for Windows Server editions, never on consumer editions.

**Comment by xf22cn** [comment]
When I created the Docker container, I used the command provided by the official documentation:

sudo docker run -d --name py-kms --restart always -p 1688:1688 -v /etc/localtime:/etc/localtime:ro pykmsorg/py-kms:latest

The host machine is a Debian 12 system specifically installed for KMS services. A clean install was used, and the system was updated to the latest version after installation. The only software installed is SSH and dcoker.

**Comment by didotb** [comment]
I have finally gotten the time to work on my PVE.

Can confirm; somehow crashes before ePID calculation on alpine, and debian 12 and 13; using latest / minimal, python3, and python3-next tags

<img width="780" height="271" alt="Image" src="https://github.com/user-attachments/assets/7839a9f2-0d3d-4bfb-a1c5-975dc7fd5644" />

I have forgotten I also have a redundant server that is currently running an older image, which is probably what was replying to the Server 2019's request.

#

### Below is the py-kms' reply after turning on debug log level

<img width="601" height="712" alt="Image" src="https://github.com/user-attachments/assets/51f93e8e-4995-47f3-bcf3-be121b6388c8" />

**Comment by xf22cn** [comment]
Today I took some time to set up a CentOS Stream 9 virtual machine and then built a py-kms server on it.

The server was minimally installed, with only SSH and Docker installed.

Unfortunately, the test still failed.

This time, I used a Windows Server 2019 virtual machine installed on a different physical host.

The error logs were identical to those I provided earlier.

**Comment by xf22cn** [comment]
I'm really hoping this issue can be fixed soon. 
I upgraded to this version without sufficient testing and didn't keep the old Docker image. 
There's no going back now…

**Comment by didotb** [comment]
you can still try to figure out which is which via trial and error of the SHA checksum of the image
checkout these images:
- [sha256:1e7072b70138f9c10af1d33acaa5b735a5199b985d879bf922e06b41b2e08a68](https://github.com/orgs/Py-KMS-Organization/packages/container/py-kms/240017505)
- [sha256:b9de6165cc1090698ff1377c56cd9b4996d61e565d9b816cdb1fe4e12bbe483a](https://github.com/orgs/Py-KMS-Organization/packages/container/py-kms/240017639)
- [sha256:27eefba7a013eebc401d802bee7ae456b14cccc7cc62d5de6c94b0eaf534c2be](https://github.com/orgs/Py-KMS-Organization/packages/container/py-kms/240017653)

I found them cause these were the most downloaded from the images last year

The previous stable `python3-next` is `sha256:6ca1dbfdb5c94fa1091e9b2b4b6969cb18f88960134bafc98ed537831d18acc8`

**Comment by didotb** [comment]
> didn't keep the old Docker image

This is another reason why there's a need to bump up the semantic versioning.
Tests will be easier once this is setup first.

**Comment by xf22cn** [comment]
The problem was resolved after rolling back the version.

Thank you very much!

**Comment by simonmicro** [comment]
What a strange error we have here. So, the last release https://github.com/Py-KMS-Organization/py-kms/pull/136 did change a bit of stuff, which should not be relevant - except that the `KmsDataBase.xml` was swapped for a newer version. This change was made due to other issues requesting it... To isolate the issue down to this specific change, can you test with different `KmsDataBase.xml` versions and see which one (does not) activate? I'm not using Windows anymore, hence I'm unwilling to test that on my own.

For this you need to start the Docker container and mount (an older) `KmsDataBase.xml` from the host OS into the container at the correct path.

This is the current database: https://github.com/Py-KMS-Organization/py-kms/blob/d006e2e587ae7748b4f425754e43df8807d064ae/py-kms/KmsDataBase.xml
This was the previous version: https://github.com/Py-KMS-Organization/py-kms/blob/0f58e9bb6fa5bed221dc3224ceba1e7832d02a90/py-kms/KmsDataBase.xml
The path you need it to mount to is: `/home/py-kms/KmsDataBase.xml`

...if we can confirm this is really caused by some unexpected answer to the requesting client due to the changed database, then we can try to pin down the specific change in there.

**Comment by simonmicro** [comment]
Also, stay tuned for #141 , in which I also fixed the server not showing errors during request processing (WTF?)... So, whenever it gets available on the `next` branch, I recommend you to redo your test with that and look for exceptions...

**Comment by didotb** [comment]
Here are the logs trying out both.
- `pykms_new_db.log` is using the current database with the link you provided;
- `pykms_old_db.log` is using the previous database with the link you provided.

I've also included the `docker-compose.yml` file I used.
Weirdly enough, sometimes it fails to start due to the log file not writable, so for this test I had to set the uid and gid used to extract the log files uploaded here.

[pykms_new_db.log](https://github.com/user-attachments/files/24010603/pykms_new_db.log)
[pykms_old_db.log](https://github.com/user-attachments/files/24010602/pykms_old_db.log)
[docker-compose.yml](https://github.com/user-attachments/files/24010601/docker-compose.yml)

---

I forgot to include that: I was indeed able to activate the Server 2019 Datacenter once again, using the old database.

**Comment by KoinzellAscheri** [comment]
I created two new Server 2019 test VMs, one Standard edition and the other Datacenter edition, and both cannot be activated with the latest version of py-kms (and so the latest version of KmsDataBase.xml).

If it may be useful, I'm using the python3 tagged version of py-kms (the one with the web interface) and it shows no ID in the "KMS EPID" column for the 2019 servers.

<img width="1436" height="133" alt="Image" src="https://github.com/user-attachments/assets/6d7d7d24-3f85-4190-bd69-7b34fc302250" />
[...]
<img width="1436" height="325" alt="Image" src="https://github.com/user-attachments/assets/d7c4b69d-726e-4fc3-a36a-316e5b8e2219" />

**Comment by KoinzellAscheri** [comment]
> This is the current database: https://github.com/Py-KMS-Organization/py-kms/blob/d006e2e587ae7748b4f425754e43df8807d064ae/py-kms/KmsDataBase.xml
> This was the previous version: https://github.com/Py-KMS-Organization/py-kms/blob/0f58e9bb6fa5bed221dc3224ceba1e7832d02a90/py-kms/KmsDataBase.xml
> The path you need it to mount to is: `/home/py-kms/KmsDataBase.xml`

I've compared the two files and reversed some of the changes for the Server 2019 entries.

(Some of the changes I didn't fix : many lines of `<Activate KmsItem="[...]" />` were removed in the three "Windows Server 2019 [...]" `<CsvlkItem>[...]<\CsvlkItem>` blocks in the XML file and I don't know if they're necessary or not. So I didn't add them again for now.)

I uploaded this fixed version of KmsDataBase.xml in my docker and it looks like it fixed the issue. I'm now able to activate my Server 2019 VMs.

Here's the fixed file :
[KmsDataBase-fix.xml](https://github.com/user-attachments/files/24198827/KmsDataBase-fix.xml)

**Comment by thadrumr** [comment]
> > This is the current database: https://github.com/Py-KMS-Organization/py-kms/blob/d006e2e587ae7748b4f425754e43df8807d064ae/py-kms/KmsDataBase.xml
> > This was the previous version: https://github.com/Py-KMS-Organization/py-kms/blob/0f58e9bb6fa5bed221dc3224ceba1e7832d02a90/py-kms/KmsDataBase.xml
> > The path you need it to mount to is: `/home/py-kms/KmsDataBase.xml`
> 
> I've compared the two files and reversed some of the changes for the Server 2019 entries.
> 
> (Some of the changes I didn't fix : many lines of `<Activate KmsItem="[...]" />` were removed in the three "Windows Server 2019 [...]" `<CsvlkItem>[...]<\CsvlkItem>` blocks in the XML file and I don't know if they're necessary or not. So I didn't add them again for now.)
> 
> I uploaded this fixed version of KmsDataBase.xml in my docker and it looks like it fixed the issue. I'm now able to activate my Server 2019 VMs.
> 
> Here's the fixed file : [KmsDataBase-fix.xml](https://github.com/user-attachments/files/24198827/KmsDataBase-fix.xml)

This updated Database fixed mine.  I was able to mount /home/py-kms as persistant on my container and update the file.  Bonus this also fixed the WebUI.

**Comment by Rileran** [comment]
I wrote a PR which should fix this issue (and future issues in a malformed KmsDataBase.xml). https://github.com/Py-KMS-Organization/py-kms/pull/143

Feel free to try it out and tell me if it works for you.

**Comment by xf22cn** [comment]
I've been following this issue closely.

I've downloaded the latest image, from January 19th.

After testing, I regret to inform you that the problem remains unresolved, and the logs are identical to those in my initial post.

However, I'm not entirely sure if this image is correct. Here's the image ID:
sha256:8c4150d4a34a56a33d39bcad11fa5c0b2e85cad34081363063a96e9e7bb6a898

**Comment by xf22cn** [comment]
@Rileran Could you please tell me how to apply your PR?

My knowledge of Docker is extremely basic; I only know how to download images and then apply them using commands.

If it's very complex, then I apologize for asking this question. You don't need to provide me with detailed steps; I will patiently wait for the next image release.

Thank you very much.

**Comment by didotb** [comment]
> Could you please tell me how to apply your PR?

You could use docker compose so you can use yaml files to edit the container config. You download their database, and add it as a volume mount to your container under `volumes:`, or `-v` for using docker-cli.
Make sure you mount as read-only (i.e. add `:ro` when using docker compose). Not sure how to do it on docker-cli.

**Comment by xf22cn** [comment]
I'm very glad this issue has been resolved in the latest update. I just pulled the latest Docker image and was able to activate Windows Server 2019 properly. Many thanks to simonmicro and everyone who helped me with this issue! Thank you!

**Comment by FDrebin** [comment]
The fix provided also resolved my issue which was weird as it kept corrupting the database or the web UI as it would error 500. Looking forward to a 1.0 release being avail via docker.

**Comment by simonmicro** [comment]
@xf22cn Thank you very much, but credit where credit is due - here to the original author of the PR in #143 😀 

@FDrebin oh - this is interesting! Even as this issue fixed the original cause for the issue on your side, maybe we could also fix the issue causing database corruption itself? Would you please consider opening a bug-report for your issue? To be perfect, a defective database would be helpful - but this may leak private information. Alternatively, you could consider dumping it into an ".sql" and masking your information from it. This would at least give me a chance to guess what went wrong.

**Comment by FDrebin** [comment]
> @FDrebin oh - this is interesting! Even as this issue fixed the original cause for the issue on your side, maybe we could also fix the issue causing database corruption itself? Would you please consider opening a bug-report for your issue? To be perfect, a defective database would be helpful - but this may leak private information. Alternatively, you could consider dumping it into an ".sql" and masking your information from it. This would at least give me a chance to guess what went wrong.
>
I will see what information I can gather, but I noticed that every other device activated perfectly until my server 2019 servers attempted to use it and as soon as they perform the KMS activation, it would fail on the client and then the web ui (of pykms) would go to error 500 and it was unrecoverable.
